import React from "react";
import Head from "next/head";

const SiteHead: React.FC = () => {
    return (
        <Head>
            <title>Basium-Masculino</title>
            <meta name="description" content="Generated by create next app" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" />
            <link
                href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@300;600;700&display=swap"
                rel="stylesheet"
            />
        </Head>
    );
};

export default SiteHead;
